import type { MobileSnapshot } from './contract'

// Fictitious preview data only. Keep the same explicit whitelist as the Rust DTO.
export const mobileMockSnapshot = {
  schemaVersion: 2,
  revision: 12,
  managerTimestampMs: 1_790_000_000_000,
  aggregate: {
    totalAccounts: 4,
    onlineAccounts: 3,
    xpPerHourTotal: 49_962_059,
    goldPerHourTotal: 2_099_773,
    goldTotal: 961_231_170,
    orbsTotal: 1_732,
  },
  accounts: [
    {
      id: 'mock-trainer-three',
      displayName: 'DemoTrainerThree',
      status: 'online',
      connectionOwner: 'background',
      level: 683,
      huntName: 'Ancient Pupitar',
      huntElapsedMs: 3_726_000,
      activePokemon: {
        name: 'Venusaur',
        level: 683,
        hp: 89,
        maxHp: 100,
        shiny: false,
        looktype: null,
        lookShiny: null,
      },
      gold: 94_062_031,
      orbs: 254,
      xpPerHour: 16_631_318,
      goldPerHour: 697_875,
      potion: { id: 70070, name: 'Golden Potion', quantity: 105 },
      ball: { id: 4, name: 'Ultra Ball', quantity: 9_173 },
      automations: {
        autoPotion: true,
        autoRevive: true,
        autoSaleLoot: true,
        autoReturnHunt: true,
        autoLockShiny: true,
        autoLockNota9: false,
        autoLockP5: true,
        captureMode: 'continuous',
        captureQueueLen: 2,
      },
    },
    {
      id: 'mock-trainer-four',
      displayName: 'DemoTrainerFour',
      status: 'online',
      connectionOwner: 'background',
      level: 684,
      huntName: 'Ancient Pupitar',
      huntElapsedMs: 8_190_000,
      activePokemon: {
        name: 'Venusaur',
        level: 684,
        hp: 86,
        maxHp: 100,
        shiny: false,
        looktype: null,
        lookShiny: null,
      },
      gold: 90_193_905,
      orbs: 0,
      xpPerHour: 16_674_127,
      goldPerHour: 700_988,
      potion: { id: 70070, name: 'Golden Potion', quantity: 99 },
      ball: { id: 4, name: 'Ultra Ball', quantity: 9_339 },
      automations: {
        autoPotion: true,
        autoRevive: true,
        autoSaleLoot: true,
        autoReturnHunt: true,
        autoLockShiny: true,
        autoLockNota9: false,
        autoLockP5: true,
        captureMode: 'continuous',
        captureQueueLen: 1,
      },
    },
    {
      id: 'mock-trainer-one',
      displayName: 'DemoTrainerOne',
      status: 'offline',
      connectionOwner: 'none',
      level: 1_048,
      huntName: 'Feebas',
      huntElapsedMs: 1_125_000,
      activePokemon: {
        name: 'Venusaur',
        level: 1_048,
        hp: 87,
        maxHp: 100,
        shiny: false,
        looktype: null,
        lookShiny: null,
      },
      gold: 700_702_652,
      orbs: 566,
      xpPerHour: 0,
      goldPerHour: 0,
      potion: { id: 70070, name: 'Golden Potion', quantity: 54 },
      ball: { id: 4, name: 'Ultra Ball', quantity: 2_740 },
      automations: {
        autoPotion: true,
        autoRevive: false,
        autoSaleLoot: true,
        autoReturnHunt: true,
        autoLockShiny: true,
        autoLockNota9: true,
        autoLockP5: false,
        captureMode: 'off',
        captureQueueLen: 0,
      },
    },
    {
      id: 'mock-trainer-two',
      displayName: 'DemoTrainerTwo',
      status: 'online',
      connectionOwner: 'browser',
      level: 644,
      huntName: 'Ancient Pupitar',
      huntElapsedMs: 4_050_000,
      activePokemon: {
        name: 'Venusaur',
        level: 644,
        hp: 78,
        maxHp: 100,
        shiny: false,
        looktype: null,
        lookShiny: null,
      },
      gold: 76_272_582,
      orbs: 912,
      xpPerHour: 16_656_614,
      goldPerHour: 700_910,
      potion: { id: 70070, name: 'Golden Potion', quantity: 42 },
      ball: { id: 4, name: 'Ultra Ball', quantity: 7_747 },
      automations: {
        autoPotion: true,
        autoRevive: true,
        autoSaleLoot: true,
        autoReturnHunt: true,
        autoLockShiny: true,
        autoLockNota9: false,
        autoLockP5: true,
        captureMode: 'until_capture',
        captureQueueLen: 1,
      },
    },
  ],
  market: {
    readerStatus: 'waiting',
    lastUpdatedAt: null,
    enabledRuleCount: 2,
    totalRuleCount: 3,
    summaries: [
      {
        itemId: 40,
        name: 'Cocoon Stone',
        category: 'stones',
        listings: 101,
        units: 9_162,
        minGold: 23_903,
        minOrb: 2,
      },
      {
        itemId: 5,
        name: 'Ultra Ball',
        category: 'balls',
        listings: 82,
        units: 7_200,
        minGold: 148_000,
        minOrb: null,
      },
      {
        itemId: 70000,
        name: 'Beast Ball',
        category: 'balls',
        listings: 95,
        units: 50_976,
        minGold: 170_000,
        minOrb: 2,
      },
    ],
    topItemSales: [
      {
        currencyGroup: 'all',
        itemName: 'Earth Stone',
        quantity: 2_140,
        transactions: 129,
        averageUnitPrice: null,
        averageGoldUnitPrice: 59_506,
        averageOrbUnitPrice: null,
      },
      {
        currencyGroup: 'all',
        itemName: 'Beast Ball',
        quantity: 913,
        transactions: 55,
        averageUnitPrice: null,
        averageGoldUnitPrice: 192_690,
        averageOrbUnitPrice: null,
      },
      {
        currencyGroup: 'gems',
        itemName: 'Cocoon Stone',
        quantity: 42,
        transactions: 9,
        averageUnitPrice: 111,
        averageGoldUnitPrice: null,
        averageOrbUnitPrice: null,
      },
    ],
    recentTransactions: [
      {
        id: 'mock-sale-1',
        occurredAt: 1_790_000_000_000,
        kind: 'item',
        currency: 'gold',
        name: 'Earth Stone',
        looktype: null,
        lookShiny: null,
        shiny: false,
        total: 843_312,
        quantity: 12,
        unitPrice: 70_276,
      },
      {
        id: 'mock-sale-2',
        occurredAt: 1_789_999_000_000,
        kind: 'pokemon',
        currency: 'orb',
        name: 'Furious Scizor Nv 100',
        looktype: null,
        lookShiny: null,
        shiny: false,
        total: 306,
        quantity: 1,
        unitPrice: null,
      },
    ],
  },
} satisfies MobileSnapshot
